[build]
  publish = "dist"
  command = "npm run build"

[functions]
  node_bundler = "esbuild"

[[edge_functions]]
  path = "/sitemap.xml"
  function = "sitemap"

[[redirects]]
  from = "/about-us"
  to = "/about"
  status = 301

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
